### ISSUE TITLE
Dradis Pro: License Renewal Link Broken

### ISSUE THREAD

**Issue by leesoh** [dradis/dradis-ce#217] opened 2018-03-20 18:13 UTC
### Steps to reproduce

Buy a Dradis Pro license. Let it get close to expiry.

### Expected behavior

A message should appear with a link to renew.

### Actual behavior

A message with a broken link appears:

![image](https://user-images.githubusercontent.com/1276654/37674238-fba8415e-2c37-11e8-88cd-4ac4224a66ae.png)

### System configuration
**Dradis version**: Dradis Pro 2.6

**Ruby version**:

**OS version**:

**Comment by etdsoft** [comment] 2018-03-20 19:14
Closing as duplicate of #185

**Closed by etdsoft** 2018-03-20 19:14 UTC
