### ISSUE TITLE
NMAP import errors

### ISSUE THREAD

**Issue by ainich** [dradis/dradis-ce#393] opened 2018-11-05 16:53 UTC
[16:48:56] There was a fatal error processing your upload:
[16:48:56] undefined method `project_id' for #<Node:0x007ff013ccc7b0> Did you mean? project project= object_id

Debian stretch, ruby 2.3.3p222

**Comment by rachkor** [comment] 2018-11-05 17:04
@ainich thanks for reaching out! Are you running Dradis CE or Pro? If CE, when did you install? If it was >8 hours ago, I'm thinking that this fix will resolve the error for you! http://discuss.dradisframework.org/t/cant-export-project-package-or-template-on-kali/609/4?u=rachkor

**Comment by ainich** [comment] 2018-11-05 17:23
CE, less then 8. Il try update

**Comment by rachkor** [comment] 2018-11-05 18:43
@ainich I've replicated this on my end as well and have escalated this to the technical team for further investigation. Stay tuned for updates!

**Comment by rachkor** [comment] 2018-11-07 16:19
@ainich we've pushed a fix (to `dradis-plugins`) that should resolve this. Could you test it and confirm as well?

**Comment by rachkor** [comment] 2018-11-09 21:20
@ainich I'm going to close this for now. Please re-open if the issue is not resolved on your end!

**Closed by rachkor** 2018-11-09 21:20 UTC
