### ISSUE TITLE
Bundler 2.4.22 is running, but your lockfile was generated with 2.3.16.

### ISSUE THREAD

**Issue by huornlmj** [dradis/dradis-ce#1206] opened 2023-11-24 16:15 UTC
### Steps to reproduce

I've no idea - I was following the instructions.

### Expected behavior
Should work.

### Actual behavior
```console
$ ./bin/setup

== Enabling default add-ons ==
== Installing dependencies ==
https://github.com/dradis/dradis-html_export.git (at rails-7-upgrade@70ccfe4) is not yet checked out. Run `bundle install` first.
Bundler 2.4.22 is running, but your lockfile was generated with 2.3.16. Installing Bundler 2.3.16 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
There was an error installing the locked bundler version (2.3.16), rerun with the `--verbose` flag for more details. Going on using bundler 2.4.22.
There was an error while trying to write to `/home/user/source/dradis-ce/vendor/bundle/ruby/3.1.0`. It is likely that you need to grant write permissions for that path.

== Command ["bundle install"] failed ==

```

### System configuration
**Dradis version**: N/A

**Ruby version**: 
```console
$ ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
```

**OS version**:
```console
$ cat /etc/issue
Ubuntu 22.04.2 LTS \n \l
```

**Comment by MattBudz** [comment] 2023-11-24 16:54
@huornlmj it looks like you have a newer version of bundler installed. Try running:
```bash
$ gem install bundler -v 2.3.16 --verbose
```

the `--verbose` flag should give us some more clues as to what the issue is if it errors out.

If bundler installs without errors, then run the setup script again
```bash
$ ./bin/setup
```

**Comment by huornlmj** [comment] 2023-11-24 16:58
@MattBudz I tried this and there was no error from your command.  But still the setup fails with the following:

```console
$ ./bin/setup

== Enabling default add-ons ==
== Installing dependencies ==
https://github.com/dradis/dradis-html_export.git (at rails-7-upgrade@70ccfe4) is not yet checked out. Run `bundle install` first.
There was an error while trying to write to `/home/user/source/dradis-ce/vendor/bundle/ruby/3.1.0`. It is likely that you need to grant write permissions for that path.

== Command ["bundle install"] failed ==

```

**Comment by MattBudz** [comment] 2023-11-24 17:02
@huornlmj looks like we are making some progress now, as this is a different error. 

When you run `$ bundle install`, are you getting any errors?

**Comment by huornlmj** [comment] 2023-11-24 17:10
I had to add some additional prerequisites (libpq-dev).  THis then worked.  But oddly, the README says to point my browser to port 3000 but Dradis is listening on port 8080 instead?

**Comment by MattBudz** [comment] 2023-11-24 17:13
the `$ ./bin/setup` script will start the server on port 8080, but going forward you will start the server using `$ bin/rails server` and that will run on port 3000. I'll make a note to update the setup script to also use port 3000 for consistency.

**Comment by huornlmj** [comment] 2023-11-24 17:25
Ok I see.  SO I should ctrl-c the current instance that started on port 8080 via the `./bin/setup` and then restart it with `./bin/rails server`?

**Comment by MattBudz** [comment] 2023-11-24 17:29
yes, `$ bin/rails server` will get you up and running on port 3000, and you'll be using that command to start the server each time going forward. 

I'm closing this issue as it sounds like you're up and running now.

**Closed by MattBudz** 2023-11-24 17:29 UTC
